services:
  - type: web
    name: isolarchecking-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --omit=dev
    startCommand: node index.js
    autoDeploy: false
