services:
  - type: web
    name: isolarchecking-backend
    env: node
    rootDir: backend
    buildCommand: |
      pip install -r backend/requirements.txt
      yarn install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: isolarchecking-frontend
    env: static
    rootDir: frontend
    buildCommand: yarn build
    staticPublishPath: dist
